---
engines:
  golint:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "grifts/**/*"
  - "**/*_test.go"
  - "*_test.go"
  - "**_test.go"
